#!/bin/bash

# test if bitbake exist; if not; fetch it and untar it
if [ ! -d bitbake-1.10.2 ]
then
        wget http://download.berlios.de/bitbake/bitbake-1.10.2.tar.gz
        tar xf bitbake-1.10.2.tar.gz
fi

# switch to the buglabs branch
cd oe-buglabs
git checkout -b buglabs-sw2.1 origin/buglabs-sw2.1
cd ..

# TOPDIR is where we are now
TOPDIR=`pwd`

# add bitbake to the path
export PATH=${TOPDIR}/bitbake-1.10.2/bin:$PATH
export BBPATH=${TOPDIR}:${TOPDIR}/oe-buglabs
export BB_ENV_EXTRAWHITE="MACHINE DISTRO TOPDIR"

if [ ! -d conf ]
then
        mkdir ${TOPDIR}/conf
fi

cp oe-buglabs/buglabs-scripts/local.conf conf/

echo $BBPATH
echo "Configuring done."
