#!/bin/bash

# test if bitbake exist; if not; fetch it and untar it
if [ ! -d bitbake-1.12.0 ]
then
        wget http://download.berlios.de/bitbake/bitbake-1.12.0.tar.gz
        tar xf bitbake-1.12.0.tar.gz
fi

# switch to the buglabs branch
cd oe-buglabs
git checkout -b buglabs-sw2.1 origin/buglabs-sw2.1
cd ..

# TOPDIR is where we are now
TOPDIR=`pwd`

# add bitbake to the path
export PATH=${TOPDIR}/bitbake-1.12.0/bin:$PATH
export BBPATH=${TOPDIR}:${TOPDIR}/oe-buglabs
export BB_ENV_EXTRAWHITE="MACHINE DISTRO TOPDIR"

if [ ! -d conf ]
then
        mkdir ${TOPDIR}/conf
fi

if [ -f conf/local.conf ]
then
	echo "Not overwriting local.conf with default."
else
	cp oe-buglabs/buglabs-scripts/local.conf conf/
fi

echo $BBPATH
echo "Configuring done."
